
--Componentes do Grupo
--82508 Adriano Matias de Souza
--82455 Carlos Cesar Rodrigues Vieira Junior
--82804 Gabriel Alves Pereira
--82680 Joao Pedro Albuquerque dos Santos
--79625 Sidnei Rocha da Costa
--83332 Victor Oliver Marques Costa

DROP SEQUENCE ALUNO_SEQ;  
DROP SEQUENCE ENDERECO_SEQ;
DROP TABLE FN_ENDERECO;
DROP TABLE FN_ALUNO; 

CREATE TABLE FN_ALUNO (
ID_ALUNO INTEGER PRIMARY KEY,
NM_ALUNO VARCHAR2(20),
SOBRENOME_ALUNO VARCHAR2(40),
CPF_ALUNO VARCHAR2(18),
EMAIL_ALUNO VARCHAR2(50),
PW_ALUNO VARCHAR2(20),
TELEFONE_ALUNO VARCHAR2(18),
RM_ALUNO VARCHAR2(5)
); 

CREATE TABLE FN_ENDERECO (
    ID_ENDERECO INTEGER PRIMARY KEY,
    CEP VARCHAR2(20),
    LOGR VARCHAR2(50),
    NUMERO VARCHAR2(10),
    BAIRRO VARCHAR2(30),
    CIDADE VARCHAR2(30),
    UF VARCHAR2(2),
    ID_ALUNO INTEGER REFERENCES FN_ALUNO(ID_ALUNO)
);

CREATE SEQUENCE ALUNO_SEQ 
INCREMENT BY 1 
START WITH 1;

CREATE SEQUENCE ENDERECO_SEQ 
INCREMENT BY 1 
START WITH 1;